## Scalars, vectors, matrices and tensors

**scalars**: float   
**vectors**: numpy.array   
**matrix and tensors**: numpy.ndarray   

_Examples_:

In [139]:
import numpy as np

def pprint(*names):
    for name in names:
        print "%s:" %(name,)
        print eval(name)
        print "\n"

def transpose(x):
    if not isinstance (x, np.ndarray):
        return x
    if x.ndim == 1:
        return x[:, np.newaxis]
    if x.shape[1] == 1:
        return x.T[0]
    return x.T 
    
def vector(*x):
    if not isinstance(x[0], list):
        return transpose(np.array(x))
    return transpose(np.array(x[0]))

def matrix(x):
    return np.array(x)

def scalar(x):
    if isinstance(x, list):
        return x[0]
    return x

In [138]:
x.T.shape

(1, 10)

In [140]:
x = vector(["x[%d]" %(i,) for i in range(10)])
y = vector(range(1,11))
pprint("x", "y")

x:
[['x[0]']
 ['x[1]']
 ['x[2]']
 ['x[3]']
 ['x[4]']
 ['x[5]']
 ['x[6]']
 ['x[7]']
 ['x[8]']
 ['x[9]']]


y:
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]




In [141]:
A = matrix([["A[%d][%d]" %(i,j) for i in range(2)] for j in range(2)])
B = matrix([[i*10+j for i in range(1, 3)] for j in range(1,3)])

pprint("A", "B")

A:
[['A[0][0]' 'A[1][0]']
 ['A[0][1]' 'A[1][1]']]


B:
[[11 21]
 [12 22]]




In [142]:
T = matrix([[["T[%d][%d][%d]" %(i, j, k) for i in range(2)] for j in range(2)] for k in range(3)])
U = matrix([[[i*100 + j*10 + k for i in range(1, 3)] for j in range(1, 3)] for k in range(1, 4)])

pprint("T", "U")

T:
[[['T[0][0][0]' 'T[1][0][0]']
  ['T[0][1][0]' 'T[1][1][0]']]

 [['T[0][0][1]' 'T[1][0][1]']
  ['T[0][1][1]' 'T[1][1][1]']]

 [['T[0][0][2]' 'T[1][0][2]']
  ['T[0][1][2]' 'T[1][1][2]']]]


U:
[[[111 211]
  [121 221]]

 [[112 212]
  [122 222]]

 [[113 213]
  [123 223]]]




In [143]:
x.ndim

2

In [144]:
x_t = transpose(x)
A_t = transpose(A)

pprint("x_t", "A_t")

x_t:
['x[0]' 'x[1]' 'x[2]' 'x[3]' 'x[4]' 'x[5]' 'x[6]' 'x[7]' 'x[8]' 'x[9]']


A_t:
[['A[0][0]' 'A[0][1]']
 ['A[1][0]' 'A[1][1]']]




In [145]:
pprint("B + B")

B + B:
[[22 42]
 [24 44]]




In [147]:
a = 2
c = 1
pprint("a*B + c")

a*B + c:
[[23 43]
 [25 45]]




In [151]:
b = vector(range(1,3))
pprint("b", "B", "B + b")

b:
[[1]
 [2]]


B:
[[11 21]
 [12 22]]


B + b:
[[12 22]
 [14 24]]




In [169]:
def mul(*args):
    def multiply(a, b):
        try:
            return np.dot(a, b)
        except ValueError:
            return np.outer(a, b)
        
    return reduce(multiply, args)

pprint("mul(B, B)")
pprint("mul(transpose(y), y)")
pprint("mul(y, y)")
pprint("mul(3, 4)")

mul(B, B):
[[373 693]
 [396 736]]


mul(transpose(y), y):
[385]


mul(y, y):
[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


mul(3, 4):
12


